### ISSUE TITLE
Is 2.1.0 already released?

### ISSUE THREAD

**Issue by odrotbohm** [thymeleaf/thymeleaf-extras-java8time#1]
The README states the current version of this is 2.1.0.RELEASE. However I can't find anything in Maven central or a tag? Is 2.1.0 already released?

If not, is there a rough ETA on this one? I'm not in a rush, I just want to avoid we do a release on our side postponing the integration with Thymeleaf and JSR-310 and find a release of the module the day after :).

**Comment by jmiguelsamper** [comment]
Hello,

sorry for the wrong number in the README. I put that one as a reminder to myself of the first stable version, but I know it is misleading, so I have just changed it to 2.1.0-SNAPSHOT.

Anyway, I want to add a couple of methods and do more testing before releasing the 2.1.0.RELEASE version, but there is no ETA for that, maybe we should release 2.1.0 and do the improvements in 2.1.1.

Regards.

**Comment by odrotbohm** [comment]
Thanks for that! I don't want to create any pressure and as it's basically an internal project here. So I'll just go ahead and do an intermediate internal release of the extension.

**Comment by jmiguelsamper** [comment]
Ok, tell us if you experience any issue with the Dialect.

2.1.0-SNAPSHOT is already in the Sonatype snapshot repository, if you can access to it.
