### ISSUE TITLE
How to Implements thymeleaf-extras-java8time on Thymeleaf 3.0.0.BETA03

### ISSUE THREAD

**Issue by mohysoka** [thymeleaf/thymeleaf-extras-java8time#12]
Hello, 
First I want to Thanks for the Developer that create such amazing code.
Right now, I am using Thymeleaf 3.0.0.BETA03 on my project, and of course i also use LocalDate on my Entity class.
It seems that thymeleaf-extras-java8time not yet compatible for Thymeleaf 3.0.0.BETA03 because of the changes the new Dialect System.
How do I implement this library on Thymeleaf 3.0.0.BETA03?
Is there a plan for modified this library for accommodating the changes?

Sorry for my bad english.
Thanks For the Great Works.. ^_^

**Comment by jmiguelsamper** [comment]
Hello,

there is a Snapshot version 3.0.0-SNAPSHOT that should work with Thymeleaf 3.

Please see http://www.thymeleaf.org/faq.html#use-snapshot how to use snapshot versions.

Regards.

**Comment by zinzia** [comment]
i have same issues with mohysoka, 
i updated thymeleaf with version 3.0.0-SNAPSHOT and i get this error

Caused by: java.lang.ClassNotFoundException: org.thymeleaf.dialect.IExpressionEnhancingDialect

how can i solved this ?

thanks

**Comment by jmiguelsamper** [comment]
If you want to try Thymeleaf 3, please use a beta version like 3.0.0.BETA03, not a snapshot version.

Make sure that the java8time dialect version is 3.0.0-SNAPSHOT.
