### ISSUE TITLE
incompatible with Thymeleaf 3.0.0 release

### ISSUE THREAD

**Issue by wiecia** [thymeleaf/thymeleaf-extras-java8time#13]
any plans to upgrade to newest thymeleaf?

**Comment by jmiguelsamper** [comment]
3.0.0-SNAPSHOT should work with Thymeleaf 3. 

Have you experienced any issue? Please give us more details about the error, we want to get more feedback before releasing it as stable.

**Comment by wiecia** [comment]
yes - snapshot version works fine, previously I was using official stable release.
thanks!
