### ISSUE TITLE
${#temporals.format(localDate1)} fails for the null parameter.

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf-extras-java8time#14]
If localDate1 is null, ${#temporals.format(localDate1)} fails with an error: java.lang.IllegalArgumentException: Cannot apply format on null.

But ${#dates.format(date1)} works fine with date1=null, it just output empty string for this case.

Can you please make ${#temporals.format(localDate1)} like {#dates.format(date1)} methods for the null parameter?

Now I need check for null like this: th:text="${localDate1} ? ${#temporals.format(localDate1)}".

Versions:
thymeleaf.version=3.0.2.RELEASE
thymeleaf-extras-java8time=3.0.0.RELEASE

**Comment by jmiguelsamper** [comment]
Fixed with the merge PR on 3.0.1-SNAPSHOT
