### ISSUE TITLE
Allows to specify FormatStyle.FULL/LONG/MEDIUM/SHORT to format TemporalObjects

### ISSUE THREAD

**Issue by foal** [thymeleaf/thymeleaf-extras-java8time#19]
I need to format LocalDate according to the document locale as a SHORT form. Now it is hardcoded as LONG

**Comment by jmiguelsamper** [comment]
'SHORT', 'MEDIUM', 'LONG' and 'FULL' can now be specified as patterns to use the standard _java.time.format.FormatStyle_ patterns.
