### ISSUE TITLE
Formatting of java.time.LocalTime broken in 3.0.2.RELEASE

### ISSUE THREAD

**Issue by vpavic** [thymeleaf/thymeleaf-extras-java8time#20]
An expression like `#temporals.format(someLocalTime, 'HH:mm:ss')`, where `someLocalTime` is an instance of `java.time.LocalTime`, will result in exception with the following root cause:

```
Caused by: java.lang.IllegalArgumentException: Cannot format object of class "java.time.LocalTime" as a date
	at org.thymeleaf.extras.java8time.util.TemporalObjects.zonedTime(TemporalObjects.java:112) ~[thymeleaf-extras-java8time-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.formatDate(TemporalFormattingUtils.java:184) ~[thymeleaf-extras-java8time-3.0.2.RELEASE.jar:3.0.2.RELEASE]
```

This looks like a regression in `3.0.2.RELEASE` and basically a reoccurrence of #2. Reverting to `3.0.1.RELEASE` addresses the problem.

**Comment by jmiguelsamper** [comment]
Hi Vedran,

Thank you very much for the bug report. We have already fixed on 3.0.3-SNAPSHOT (see https://www.thymeleaf.org/faq.html#use-snapshot). If you have some time to confirm that the bugfix works for you, we will integrate it into 3.0.3.RELEASE

Just for the sake of documentation, it wasn't a regression of #2

**Comment by vpavic** [comment]
Thanks for the feedback @jmiguelsamper - I've tested `3.0.3-SNAPSHOT` and can confirm the problem is addressed. :+1:

**Comment by vpavic** [comment]
Sorry to comment on a closed issue, but can you provide the status of `3.0.3.RELEASE`? According to [commit history](https://github.com/thymeleaf/thymeleaf-extras-java8time/commits/3.0-master), it appears that it was supposed to be released on December 23rd, but there's no sign of it in [Maven Central](https://search.maven.org/search?q=g:org.thymeleaf.extras%20AND%20a:thymeleaf-extras-java8time&core=gav)? Thanks!

**Comment by jmiguelsamper** [comment]
I'm sorry, it seems that something went wrong with the release.

I've uploaded again to Maven Central and I can see it at https://repo1.maven.org/maven2/org/thymeleaf/extras/thymeleaf-extras-java8time/3.0.3.RELEASE/ but it does not appear yet on public searches. I hope it will be replicated in a few hours.

Otherwise, I'll further investigate.
