### ISSUE TITLE
Add support for HijrahDate, JapaneseDate, MinguoDate and ThaiBuddhistDate

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf-extras-java8time#23]
They are all implementing classes of the java.time.temporal.Temporal interface.

**Comment by aparsons** [comment]
@jmiguelsamper I took a crack at what supporting HijrahDate could look like. I mainly looked for online documentation to put this together. This code allows for Hijrah dates to be parsed and formatted.

https://github.com/thymeleaf/thymeleaf-extras-java8time/compare/3.0-master...aparsons:hijrahdate-demo

**Comment by jmiguelsamper** [comment]
@aparsons looks very good, thank you for that. I will take a closer look to it and probably integrate it into the main code.

**Comment by danielfernandez** [comment]
Closing for now given lack of reported impact from users, in order to simplify towards integration in Thymeleaf core.
