### ISSUE TITLE
Idea: Convert to time ago in words

### ISSUE THREAD

**Issue by aparsons** [thymeleaf/thymeleaf-extras-java8time#24]
The PHP framework CakePHP has a date formatting method to convert a date into a human-friendly string like `2 months, 2 weeks, 6 days ago`. What are thoughts on adding similar functionality?

- https://book.cakephp.org/3.0/en/core-libraries/time.html#formatting-relative-times
- https://github.com/cakephp/cakephp/blob/3ddec46367e4b5aa6a2dc59558f4f9daf8d82c95/src/I18n/RelativeTimeFormatter.php#L94

**Comment by jmiguelsamper** [comment]
I will leave this ticket open for future discussion but currently I see a couple of difficulties on implementing it:

1. We try to mimic the Thymeleaf core _#dates_ utilities but it currently doesn't have a similar feature
2. While getting an English language implementation seems quite straightforward, localised implementations for other languages might be difficult to achieve.

**Comment by danielfernandez** [comment]
Closing for now given lack of reported impact from users, in order to simplify towards integration in Thymeleaf core.
