### ISSUE TITLE
Does not work with OffsetDateTime

### ISSUE THREAD

**Issue by hal8k** [thymeleaf/thymeleaf-extras-java8time#26]
Hi, 

Thanks for the library. 

I am trying to format an `OffsetDateTime` under `3.0.3.RELEASE` e.g. 

`"${#temporals.format(offsetDateTime, 'MM/dd/yyyy HH:mm:ss')}">`

and it is throwing an exception

`Caused by: java.lang.IllegalArgumentException: Cannot format object of class "java.time.OffsetDateTime" as a date
	at org.thymeleaf.extras.java8time.util.TemporalObjects.zonedTime(TemporalObjects.java:114)
	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.formatDate(TemporalFormattingUtils.java:184)`

Looking at the `zonedTime` function, there is no if-branch for `OffsetDateTime`. I did also notice this issue - https://github.com/thymeleaf/thymeleaf-extras-java8time/issues/3 - however that issue says that it should be resolved?

**Comment by hal8k** [comment]
Tested with thymeleaf-extras-java8time-3.0.4-SNAPSHOT and it works.

Is there any chance of a release soon?

**Comment by jmiguelsamper** [comment]
Hi,

I see this covered at https://github.com/thymeleaf/thymeleaf-extras-java8time/blob/2881348cccba5465b04e9aa1235b3be8cd358d75/src/test/java/org/thymeleaf/extras/java8time/expression/TemporalsFormattingTest.java#L98 and https://github.com/thymeleaf/thymeleaf-extras-java8time/blob/2881348cccba5465b04e9aa1235b3be8cd358d75/src/main/java/org/thymeleaf/extras/java8time/util/TemporalObjects.java#L110

Not sure why it did not work for you. Anyway, as you confirmed that it works OK with the latest version, I've scheduled the release of 3.0.4.RELEASE, it should be available on Maven Central in a couple of hours.
