### ISSUE TITLE
Incorrect formatted date

### ISSUE THREAD

**Issue by jamesdbaker** [thymeleaf/thymeleaf-extras-java8time#27]
I have a LocalDate object. If this is set to `2019-12-30` or `2019-12-31`, then the following formatting shows the incorrect date (notice the year):

    <p th:text="${#temporals.format(event.deadline, 'dd MMM YYYY')}"></p>

Gives `30 Dec 2020` and `31 Dec 2021` respectively. The adjacent dates give `29 Dec 2019` and `01 Jan 2020` as expected.

I am using Spring Boot 1.5.22.RELEASE, which uses thymeleaf-extras-java8time 2.1.0.RELEASE.

**Comment by jmiguelsamper** [comment]
I think you should use yyyy for the year pattern instead of YYYY, please see https://stackoverflow.com/questions/8686331/y-returns-2012-while-y-returns-2011-in-simpledateformat
