### ISSUE TITLE
Temporals format

### ISSUE THREAD

**Issue by xen59** [thymeleaf/thymeleaf-extras-java8time#28]
I'm using 

>           <dependency>
>             <groupId>org.thymeleaf.extras</groupId>
>             <artifactId>thymeleaf-extras-java8time</artifactId>
>             <version>2.1.0.RELEASE</version>
>         </dependency>

I'm trying:
`<p th:text="${#temporals.format(date, 'SHORT' )}"></p>`

I got : 

> org.thymeleaf.exceptions.TemplateProcessingException: Error formatting date for locale fr_FR (preview)
> 	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.formatDate(TemporalFormattingUtils.java:167)
> 	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.format(TemporalFormattingUtils.java:68)
> 	at org.thymeleaf.extras.java8time.expression.Temporals.format(Temporals.java:218)
> 	at sun.reflect.GeneratedMethodAccessor467.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 
> Caused by: java.lang.IllegalArgumentException: Unknown pattern letter: R
> 	at java.time.format.DateTimeFormatterBuilder.parsePattern(DateTimeFormatterBuilder.java:1661)
> 	at java.time.format.DateTimeFormatterBuilder.appendPattern(DateTimeFormatterBuilder.java:1570)
> 	at java.time.format.DateTimeFormatter.ofPattern(DateTimeFormatter.java:560)
> 	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.formatDate(TemporalFormattingUtils.java:163)
> 	... 227 common frames omitted

What did I do wrong?

**Comment by danielfernandez** [comment]
This feature was added in version 3.0.2.
