### ISSUE TITLE
Improve support for LocaleDate and LocalTime

### ISSUE THREAD

**Issue by michaelkrog** [thymeleaf/thymeleaf-extras-java8time#33]
When specifically using LocalDate and LocaleTime, I would expect that the date parts I intentionally left out by NOT using LocalDateTime would not be output using #temporals.format().

### Example
If I create a new LocalDate like this: `var date = new LocalDate(2022,1,9);` 
and try to format it with thymeleaf like this: `<span th:text="${#temporals.format(date, 'SHORT')}></span>` 

then I would expect it to become somewhat like: `<span>2022-01-09</span>` 
and not: `<span>2022-01-09, 00:00 AM</span>` which is the current case.

**Comment by danielfernandez** [comment]
Closing this for being covered by PR #34 in process of being merged. Thanks.
