### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by BernhardLenz** [thymeleaf/thymeleaf-extras-java8time#35]
It appears that Version 3.1.0.RELEASE of thymeleaf-extras-java8time is not available in the mvnrepository.com and according to maven the latest 3.0.4.RELEASE of has a bunch of security vulnerabilities. 

When will 3.1.0 be pushed to mvnrepository and will it fix the same vulnerabilities that 3.0.4 has?

**Comment by jmiguelsamper** [comment]
Not sure about those security vulnerabilities but note that, as of Thymeleaf 3.1, this module has been integrated into the Thymeleaf core, please see https://www.thymeleaf.org/doc/articles/thymeleaf31whatsnew.html#core-support-for-the-java.time-package
