### ISSUE TITLE
Is it possible to specify a locale for date patterns?

### ISSUE THREAD

**Issue by mscharhag** [thymeleaf/thymeleaf-extras-java8time#5]
Date patterns like `EEEE, d MMMM, yyyy` are locale specific. Unfortunately it does not seem to be possible to pass a locale parameter to `format()`.

E.g.:

```
${#temporals.format(temporal, 'EEEE, d MMMM, yyyy', 'en')}
${#temporals.format(temporal, 'EEEE, d MMMM, yyyy', myLocale)}
```

Is there another way to do this?

**Comment by ultraq** [comment]
Currently, no, the API doesn't provide a way to pass in the locale on a method-by-method basis (this dialect is initialized with the locale from the Thymeleaf processing context, which either comes from the request locale, or the locale the server resides on).  This should be a useful enhancement though to allow devs to specify a locale.

**Comment by jmiguelsamper** [comment]
@mscharhag Thank you very much for your pull request. Could you explicitely agree with the contributing terms and conditions on https://github.com/thymeleaf/thymeleaf-dist/blob/master/CONTRIBUTING.markdown ?

A simple comment here will be enough.

**Comment by mscharhag** [comment]
@jmiguelsamper I agree with the contributing conditions.

**Comment by jmiguelsamper** [comment]
Thanks Michael. The fix is available in the latest snapshot.

**Comment by jmiguelsamper** [comment]
@mscharhag I will add you to the list of contributors at http://www.thymeleaf.org/team.html
Please tell me if you prefer not to be listed there.

**Comment by ekorn** [comment]
I don't want to open this Issue but I tried`${#temporals.format(temporal, 'EEEE, d MMMM, yyyy', 'en')}`and get a Exception 

```
Caused by: java.lang.IllegalArgumentException: Unable to convert type java.lang.String of en to type of java.util.Locale
    at ognl.OgnlOps.convertValue(OgnlOps.java:608)
....
```

 if I use`${#temporals.format(temporal, 'EEEE, d MMMM, yyyy', en)}` without the single quotes, no Exception is thrown but the locale does not change. My standard loace is "de". So bit of documentation would be helpful how to call the function from the template. My Test looks like this:

```
    @Test
    public void testFormatTemporalWithPatternWithThymeleaf() {
        TemplateEngine templateEngine =  new TemplateEngine();
        templateEngine.addDialect(new Java8TimeDialect());
        Context thymeleafContext = new Context();   

        Temporal time =LocalDateTime.of(1993, 02, 25, 0, 0);
        thymeleafContext.setVariable("person_geburtsdatum2", time);

        String renderedString = "";
        //thymeleafContext.setLocale(new Locale("en"));

        String mitLocale = "<span th:text=\"${#temporals.format(person_geburtsdatum2, 'EEEE, d MMMM, yyyy', en)}\">25. Januar 1993</span>";
        String mitLocaleGerendert = "<span>Thursday, 25 February, 1993</span>"; 
        renderedString = templateEngine.process(mitLocale, thymeleafContext);   
        System.out.println(renderedString);
        assertEquals(mitLocaleGerendert, renderedString);
    }
```

**Comment by jmiguelsamper** [comment]
Hi,

the locale parameter must be a java.util.Locale object. This is an optional parameter. If not present, it will user the browser or default locale (depending on the environment).

**Comment by ekorn** [comment]
So I can not output a German and a English Date (that include full day or month names) in one Template without changing the browsers locale or on the serverside the locale of the context ?

**Comment by jmiguelsamper** [comment]
Yes, you can format dates with different locales in the same template, you just have to use a java.util.Locale object as an argument.

Usually, the user will have selected some locale so you could set that locale in the context.

**Comment by ekorn** [comment]
ahh thanks a lot. My test works now:

```
    @Test
    public void testFormatTemporalWithPatternWithThymeleaf() {
        TemplateEngine templateEngine =  new TemplateEngine();
        templateEngine.addDialect(new Java8TimeDialect());
        Context thymeleafContext = new Context();   

        Temporal time =LocalDateTime.of(1993, 02, 25, 0, 0);
        thymeleafContext.setVariable("person_geburtsdatum2", time);
        thymeleafContext.setVariable("en", new Locale("en"));

        String renderedString = "";
        thymeleafContext.setLocale(new Locale("en"));

        String mitLocale = "<span th:text=\"${#temporals.format(person_geburtsdatum2, 'EEEE, d MMMM, yyyy', en)}\">25. Januar 1993</span>";
        String mitLocaleGerendert = "<span>Thursday, 25 February, 1993</span>"; 
        renderedString = templateEngine.process(mitLocale, thymeleafContext);   
        System.out.println(renderedString);
        assertEquals(mitLocaleGerendert, renderedString);
    }
```
